### ISSUE TITLE
hey man when are you gonna come back to SS13?

### ISSUE THREAD

**Issue by Iamgoofball** [Uristqwerty/CraftGuide#19]
adamantite and mythril are still unfinished at /tg/

**Comment by Uristqwerty** [comment]
I suspect you are talking to the wrong Urist, as I don't recall working on anything related to either of those. I mainly worked on bay, at most contributing one or a few self-contained systems to /tg/ (transit tubes, *maybe* one or two others that might have been offered in forum posts but I have no idea if they ever actually got added).

**Comment by Uristqwerty** [comment]
Did you ever find whoever you were looking for?

I'm going to close this issue, as it's not related to the contents of the repo it's posted on, but I hope everything ultimately worked out (and see no problem with leaving the issue unlocked for future communication, if other channels are not available/convenient).
