### ISSUE TITLE
Not building after cloning

### ISSUE THREAD

**Issue by svgorbunov** [Uristqwerty/CraftGuide#23]
I use the command `gradlew build`.

First error occurs:

`Could not find property 'curseForgeApiKey' on root project 'CraftGuide'.`

After specifying the private guid from curse.com the following error

`A problem occurred configuring root project 'CraftGuide'.
> java.lang.NullPointerException (no error message)`

Not enough instructions to build your project.

Thanks.

**Comment by Uristqwerty** [comment]
For the API key, apparently back when I first set it up, the page on
ForgeGradle's GitHub wiki describing it did not include anything about
handling an undefined key, though a section was later added. A month or
two ago, though, it seemed as if that wiki page had been deleted for
some reason (moved elsewhere? But for a developer tool, they should
really have at least left a "see elsewhere" page, not outright deleted it).

I thought I had encountered something similar when trying to set it up
to work on during december, but all I can find is a change of

-    apiKey = project.curseForgeApiKey
+    apiKey = project.hasProperty('curseForgeApiKey')?
project.curseForgeApiKey : ''

though I have vague memories of encountering issues when one of the
files had the wrong line endings for the system I was using (probably
was gradlew, though).

**Comment by svgorbunov** [comment]
@Uristqwerty Thanks for the reply.

This solves the problem with error 

> Could not find property 'curseForgeApiKey' on root project 'CraftGuide'.

but does not solve the problem with the error

> `A problem occurred configuring root project 'CraftGuide'.

> java.lang.NullPointerException (no error message)`

As I understand it, the problem is caused by gradle plugin 'liteloader'. Such a hard decision as removing it from the build process solves the problem and the project will build successfully.

Unfortunately, I have not found the gradle plugin 'liteloader' documentation to try to correct the error more elegantly. Could you try to find a solution to the problem, once you've decided to support the LiteLoader?

P.S.: I don't use LiteLoader and its support doesn't interest me, but your mod I really like. Thanks!

**Comment by Uristqwerty** [comment]
I can't recall when, but I think I had some issues with it at some 
point, it would be easiest to just comment out those parts of 
build.gradle. It looks like I did exactly that on the mc18 branch, and 
never got around to finding the actual cause.

The liteloader plugin was part of ForgeGradle, unless that has changed 
in more recent versions. Hopefully it isn't something obscure to do with 
gradle/ForgeGradle caching specific files from many months ago.
